### ISSUE TITLE
Question: How long does it take to program on the connected mote?(Compilation Error because of toolchain installation)

### ISSUE THREAD

**Issue by maroufi** [iot-chalmers/BlueFlood#2]
Congratulations to the ‌BlueFlood team for this successful project.
I apologize in advance for my poor English.
I tried to have a testbed and run project on nrf52840 board. I faced to this point that programming on the board with
"make dirty-channel.flash" does not have result. I see this log without any progress.
![pic](https://user-images.githubusercontent.com/13234572/130757797-104a4abe-7fe3-44d3-a405-afab008b109c.PNG)

What's the reason of this issue? And How can I tell you more detail about this try.

**Comment by olafland** [comment]
It should work out of the box, i.e., you should see some startup info from Contiki directly.

**Comment by beshrns** [comment]
Hi Salman,

I see in your picture error messages directly when it tries to flash the
binary in the sensor. It indicates that the program was not loaded on your
device. Please consult the installation procedure of the tool chain.

Best,
Beshr

**Comment by maroufi** [comment]
Hi Beshr.

Thanks for your helpful response. That error was related to this bash file [https://github.com/iot-chalmers/BlueFlood/blob/master/cpu/arm/nrf52x/nrfjprog.sh](url) and based on my research, in this bash file there are a few deprecated syntax as it mentioned on this page [https://wiki.bash-hackers.org/scripting/obsolete](url). I can make a pull request for this.

Thank you.
